### ISSUE TITLE
Is there any branch that fully supports Lua 5.3 syntax?

### ISSUE THREAD

**Issue by w4454962** [fperrad/LuaJIT#1]

**Comment by fperrad** [comment]
if you speak about the new operators introduced by Lua 5.3:
- the branch [op53_sugar](https://github.com/fperrad/LuaJIT/tree/op53_sugar) is bugged, see https://github.com/LuaJIT/LuaJIT/pull/317
- the branch [op53](https://github.com/fperrad/LuaJIT/tree/op53) (used by https://github.com/LuaJIT/LuaJIT/pull/312) is incomplete (only x86), out dated but it is the better starting point for some experiments.

But Lua 5.3 also introduces a distinction between `integer` and `float`, and previously Lua 5.2 introduces `_ENV`; there is nothing for that.

**Comment by fsfod** [comment]
LuaJIT's dual number build option does kind of give you an integer type but its mostly just behind the scenes .
